### ISSUE TITLE
Add requirements.txt for dependencies

### ISSUE THREAD

**Issue by iporsut** [zentetsukenz/openai_gym#1]
You can add file `requirements.txt` for dependencies for project.
It is text file that list of dependencies library per line.

e.g.

```
numpy
```

Then after who clone this project can use `pip` to install dependencies with `-r` options.

e.g.

```
pip install -r requirements.txt
```

**Comment by zentetsukenz** [comment]
👍 Thank you @iporsut will do krub

**Comment by zentetsukenz** [comment]
@iporsut requirements.txt was add by this commit https://github.com/zentetsukenz/openai_gym/commit/b74e6a6c833fe49ee3b06670ad82fcb2119f0e45

closing na
